# Generated by Django 4.2.2 on 2023-08-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolla_dst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('alt_dst', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bolla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizioni', models.JSONField(default=dict)),
                ('qta', models.JSONField(default=dict)),
                ('um', models.JSONField(default=dict)),
                ('note', models.JSONField(default=dict)),
                ('lavorazione', models.CharField(max_length=50)),
                ('respSpedizione', models.CharField(max_length=50)),
                ('dataTrasp', models.DateField()),
                ('aspetto', models.CharField(max_length=50)),
                ('sameAddress', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dst', to='Bolle.bolla_dst')),
                ('dst2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dst2', to='Bolle.bolla_dst')),
            ],
        ),
    ]
