# Generated by Django 4.2.2 on 2023-08-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bolle', '0003_bolla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bolla',
        ),
    ]
