# Generated by Django 4.2.2 on 2023-08-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bolle', '0004_delete_bolla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizioni', models.JSONField(default=dict)),
                ('qta', models.JSONField(default=dict)),
                ('um', models.JSONField(default=dict)),
                ('note', models.JSONField(default=dict)),
                ('lavorazione', models.CharField(max_length=50)),
                ('respSpedizione', models.CharField(max_length=50)),
                ('dataTrasp', models.DateField()),
                ('aspetto', models.CharField(max_length=50)),
                ('sameAddress', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dst', to='Bolle.bolla_dst')),
                ('dst2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dst2', to='Bolle.bolla_dst')),
            ],
        ),
    ]
