# Generated by Django 4.2.2 on 2023-08-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bolle', '0005_bolla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolla',
            name='dst2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dst2', to='Bolle.bolla_dst'),
        ),
    ]
