# Generated by Django 4.2.2 on 2023-08-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bolle', '0006_alter_bolla_dst2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bolla',
            unique_together={('number', 'year')},
        ),
    ]
