# Generated by Django 4.2.2 on 2023-06-27 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_for_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_feedback_comment_feedback_stars_feedback_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'product')},
        ),
    ]
