# Generated by Django 4.1.7 on 2023-06-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_sm_2_delete_product_sm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_sm_2',
        ),
    ]
