# Generated by Django 4.1.7 on 2023-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sm',
            name='available_sizes',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='product_sm',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
