# Generated by Django 4.1.7 on 2023-06-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_sm_available_sizes_product_sm_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sm',
            name='available_sizes',
            field=models.JSONField(default=dict),
        ),
    ]
