# Generated by Django 4.2.2 on 2023-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_sm_available_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('available_sizes', models.JSONField(default=dict)),
                ('pid', models.AutoField(db_column='pid', primary_key=True, serialize=False)),
            ],
        ),
    ]
