# Generated by Django 4.2.2 on 2023-06-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_sm',
        ),
    ]
