# Generated by Django 4.2.2 on 2023-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_product_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.TextField(max_length=100),
        ),
    ]
