# Generated by Django 4.2.2 on 2023-06-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_tags_product_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_tags',
        ),
        migrations.AddField(
            model_name='product',
            name='category_tags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='product.tag'),
            preserve_default=False,
        ),
    ]
