# Generated by Django 4.2.2 on 2023-06-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_category_tags_product_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_tags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_with_color_tags', to='product.tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category_tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_with_category_tags', to='product.tag'),
        ),
    ]
