# Generated by Django 4.2.2 on 2023-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_color_tags_alter_product_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_tags',
        ),
        migrations.AddField(
            model_name='product',
            name='category_tags',
            field=models.ManyToManyField(related_name='products_with_category_tags', to='product.tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tags',
            field=models.ManyToManyField(related_name='products_with_color_tags', to='product.tag'),
        ),
    ]
