# Generated by Django 4.2.2 on 2023-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_category_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nome',
            new_name='noame',
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
