# Generated by Django 4.2.2 on 2023-06-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_nome_tag_noame_tag_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='noame',
            new_name='name',
        ),
    ]
