# Generated by Django 4.2.2 on 2023-06-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='product',
        ),
    ]
