# Generated by Django 4.2.2 on 2023-06-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_for_sale'),
        ('seller', '0002_remove_stats_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='product',
            field=models.ForeignKey(default=619, on_delete=django.db.models.deletion.CASCADE, to='product.product', unique=True),
            preserve_default=False,
        ),
    ]
