# Generated by Django 4.2.2 on 2023-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_stats_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='n_feedback',
            field=models.IntegerField(default=0),
        ),
    ]
