# Generated by Django 4.2.2 on 2023-06-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_tag_name'),
        ('seller', '0005_alter_stats_avg_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
