# Generated by Django 4.2.2 on 2023-09-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolle_vecchie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bolle_old',
        ),
    ]
