# Generated by Django 4.2.2 on 2023-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolle_vecchie', '0002_delete_bolle_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolle_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('anno', models.IntegerField()),
            ],
            options={
                'unique_together': {('numero', 'anno')},
            },
        ),
    ]
