# Generated by Django 4.2.2 on 2023-09-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_log',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
