# Generated by Django 4.2.2 on 2023-08-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_method', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0)),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
