# Generated by Django 4.2.2 on 2023-06-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_feedback_unique_together'),
        ('checkout', '0004_alter_checkout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address'),
        ),
    ]
