# Generated by Django 4.1.7 on 2023-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=20),
            preserve_default=False,
        ),
    ]
