# Generated by Django 4.1.7 on 2023-06-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='validity',
            field=models.DateTimeField(null=True),
        ),
    ]
