# Generated by Django 4.1.7 on 2023-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.JSONField(null=True),
        ),
    ]
