# Generated by Django 4.2.2 on 2023-06-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
