# Generated by Django 4.2.2 on 2023-06-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_tag_name'),
        ('cart', '0007_cart_checked_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_in_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=5)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products_in_cart',
            field=models.ManyToManyField(related_name='product_in_cart', to='cart.product_in_cart'),
        ),
    ]
