# Generated by Django 4.2.2 on 2023-06-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_product_in_cart_cart_products_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
