# Generated by Django 4.2.2 on 2023-06-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_tag_name'),
        ('cart', '0009_remove_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_in_cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
